require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/Banuba/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'vesdkreactnativeintegrationsample' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  sdk_version = '1.24.1'

  pod 'BanubaAudioBrowserSDK', '1.24.2' #optional
  pod 'BanubaUtilities', '1.24.2'
  pod 'BanubaARCloudSDK', sdk_version #optional
  pod 'BanubaVideoEditorSDK', sdk_version
  pod 'BanubaMusicEditorSDK', sdk_version
  pod 'BanubaOverlayEditorSDK', sdk_version
  pod 'BanubaEffectPlayer', sdk_version #optional
  pod 'BanubaSDK', sdk_version #optional
  pod 'BanubaSDKSimple', sdk_version
  pod 'BanubaSDKServicing', sdk_version
  pod 'VideoEditor', sdk_version
  pod 'BanubaVideoEditorGallerySDK', sdk_version #optional
  pod 'BanubaLicenseServicingSDK', sdk_version
  pod 'BanubaVideoEditorTrimSDK', sdk_version
  # pod 'BanubaTokenStorageSDK', '1.23.0' #optional

  pod 'BNBLicenseUtils', sdk_version

  pod 'VEExportSDK', sdk_version
  pod 'VEEffectsSDK', sdk_version
  pod 'VEPlaybackSDK', sdk_version

  # Uncomment the code below to enable Flipper.
  #
  # You should not install Flipper in CI environments when creating release
  # builds, this will lead to significantly slower build times.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work.
  #
  #  use_flipper!
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end
end
