require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/Banuba/specs.git'

platform :ios, '11.0'

target 'vesdkreactnativeintegrationsample' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'BanubaVideoEditorSDK', '1.0.18'
  pod 'BanubaMusicEditorSDK', '1.0.18'
  pod 'BanubaOverlayEditorSDK', '1.0.18'
  pod 'BanubaSDKSimple', '1.0.18'
  pod 'BanubaSDKServicing', '1.0.18'
  pod 'VideoEditor', '1.0.18'
  pod 'BanubaARCloudSDK', '1.0.18'
  pod 'BNBLicenseUtils', '1.0.17'
  pod 'BanubaAudioBrowserSDK', '1.0.18'
  pod 'BanubaUtilities', '1.0.18'
  pod 'BanubaVideoEditorGallerySDK', '1.0.18'
  pod 'BanubaLicenseServicingSDK', '1.0.18'
  pod "BanubaEffectPlayer", '1.0.17'
  pod "BanubaSDK", '1.0.18'

  # Uncomment the code below to enable Flipper.
  #
  # You should not install Flipper in CI environments when creating release
  # builds, this will lead to significantly slower build times.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work.
  #
  #  use_flipper!
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end
end
