require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'git@github.com:Banuba/specs.git'

platform :ios, '11.0'

target 'vesdkreactnativeintegrationsample' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'BanubaEffectPlayer', '0.0.10'
  pod 'BanubaVideoEditorSDK', '0.0.14'
  pod 'BanubaAudioBrowserSDK', '0.0.14'
  pod 'BanubaMusicEditorSDK', '0.0.14'
  pod 'BanubaOverlayEditorSDK', '0.0.14'
  pod 'BanubaSDK', '0.0.14'
  pod 'VideoEditor', '0.0.14'
  pod 'BanubaARCloudSDK', '0.0.14'

  # Uncomment the code below to enable Flipper.
  #
  # You should not install Flipper in CI environments when creating release
  # builds, this will lead to significantly slower build times.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work.
  #
  #  use_flipper!
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end
end
